/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyInterface */

#ifndef _Included_MyInterface
#define _Included_MyInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyInterface
 * Method:    ISC_SimiComputing
 * Signature: ([D[D[IIIZ[C[CDI)D
 */
JNIEXPORT jdouble JNICALL Java_MyInterface_ISC_1SimiComputing
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jintArray, jint, jint, jboolean, jcharArray, jcharArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
