/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TestInterface */

#ifndef _Included_TestInterface
#define _Included_TestInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TestInterface
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_TestInterface_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
